spring:
  application:
    name: recipe-finder
  datasource:
    url: jdbc:postgresql://ec2-54-83-201-84.compute-1.amazonaws.com:5432/d42ci7osqr08hh
    username: ewitqzqszbbtpl
    password: 7e0d5baba7c802129f4382703d803123ca301e34176ecfec44a2470b7d0248ab
    hikari:
      connectionTimeout: 3000
      idleTimeout: 600000
      maxLifetime: 1800000
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate.ddl-auto: create
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 80

jwt:
  secret: secret