spring:
  application:
    name: recipe-finder
  datasource:
    url: jdbc:postgresql://ec2-3-208-224-152.compute-1.amazonaws.com:5432/dabog5qjort3h
    username: csezqgvuswqgax
    password: 46b6747dc484f87e2ad35f4879638db10efdbe74a7e451ab732344ba7bb63096
    hikari:
      connectionTimeout: 3000
      idleTimeout: 600000
      maxLifetime: 1800000
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate.ddl-auto: create
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 80

jwt:
  secret: secret